apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
  annotations:
    kubernetes.io/change-cause: "first version 6.14.1"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 4
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.14.1
          ports:
            - containerPort: 9898
