apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-backend
  ports:
  - port: 5000
    targetPort: 5000
    # Здесь можно тоже использовать переменную, если хочешь разные порты
    nodePort: {{ if eq .Release.Namespace "prod" }}30051{{ else }}30050{{ end }}