apiVersion: apps/v1
kind: Deployment
metadata:
  name: impatient
spec:
  selector:
    matchLabels:
      app: impatient
  template:
    metadata:
      name: impatient
      labels:
        app: impatient
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.15.0
          ports:
            - name: http
              containerPort: 9898
          livenessProbe:
            httpGet:
              path: /delay/2
              port: http
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 3
            timeoutSeconds: 3
