apiVersion: v1
kind: Pod
metadata:
  name: count
spec:
  restartPolicy: Never
  containers:
    - name: count
      image: busybox:1.38
      command: ["sh", "-c"]
      args:
        [
          "echo 1; sleep 1; echo 2; sleep 1; echo 3; sleep 1; echo 4; sleep 1; echo 5",
        ]
