apiVersion: v1
kind: Pod
metadata:
  name: greeter
spec:
  containers:
    - name: greeter
      image: busybox:1.38
      env:
        - name: name
          value: "WaFF"
      command: ["sh", "-c"]
      args:
        - |
          while true;do
            echo $(name)
            sleep 5
          done
