apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        default_type text/plain;

        location / {
            return 200 "nginx says hi. Try /app/\n";
        }

        location /app/ {
            proxy_pass http://podinfo/;
        }
    }
