apiVersion: v1
kind: Pod
metadata:
  name: site
spec:
  containers:
    - name: nginx
      image: nginx:1.30-alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: config
  volumes:
    - name: config
      configMap:
        name: site
