apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
    - name: busybox
      image: busybox:1.38
      restartPolicy: Never
      env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: api-key
              key: token
      command: ["sh", "-c", 'echo "the token is $TOKEN"; sleep 3600']
