apiVersion: apps/v1
kind: Deployment
metadata:
  name: big
spec:
  replicas: 1
  selector:
    matchLabels:
      size: big
  template:
    metadata:
      name: big
      labels:
        size: big
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.15.0
          resources:
            requests:
              cpu: 5
