apiVersion: v1
kind: Pod
metadata:
  name: guaranteed
spec:
  containers:
    - name: guaranteed
      image: ghcr.io/stefanprodan/podinfo:6.15.0
      resources:
        requests:
          memory: 0.4Gi
          cpu: 400m
        limits:
          memory: 0.4Gi
          cpu: 400m
