apiVersion: v1
kind: Pod
metadata:
  name: memhog
spec:
  containers:
    - name: memhog
      image: busybox:1.38
      command: ["sh", "-c", "echo eating memory...; tail /dev/zero"]
      resources:
        requests:
          memory: "32Mi"
        limits:
          memory: "64Mi"
