apiVersion: v1
kind: Pod
metadata:
  name: secret-file
spec:
  containers:
    - name: busybox11
      image: busybox:1.38
      restartPolicy: Never
      volumeMounts:
        - mountPath: /etc/api/
          name: secret-env
      command: ["sh", "-c", 'echo "the token is $TOKEN"; sleep 3600']
  volumes:
    - name: secret-env
      secret:
        secretName: api-key
