apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: shorty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:17
          name: postgres
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: shorty
spec:
  ports:
    - name: 5432-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: shorty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
        serviceName: postgres
    spec:
      containers:
        - image: postgres:17
          name: postgres
          resources: {}
